version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "Asia/Seoul"
    groups:
      ci-deps:
        patterns: ["*"]
