name: Mirror upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest

    environment:
      name: release

    steps:
      - run: |
          git clone --mirror 'https://github.com/abseil/abseil-cpp' && cd abseil-cpp.git
          git push --force --no-mirror --all --follow-tags \
            "https://${GITHUB_TOKEN}@github.com/jnooree/abseil-cpp"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  test-build:
    needs: mirror
    uses: ./.github/workflows/_build.yml
    with:
      ref: master

concurrency:
  group: mirror-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
