name: Mirror upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest

    environment:
      name: release

    outputs:
      ref: ${{ steps.checkout.outputs.ref }}

    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          repository: abseil/abseil-cpp
          fetch-depth: 0

      - run: git push --force --mirror 'https://github.com/jnooree/abseil-cpp.git'
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  test-build:
    needs: mirror
    uses: ./.github/workflows/_build.yml
    with:
      ref: ${{ needs.mirror.outputs.ref }}

concurrency:
  group: mirror-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
