name: Mirror upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest

    environment:
      name: release

    outputs:
      ref: ${{ steps.checkout.outputs.ref }}

    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          repository: abseil/abseil-cpp
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}

      - run: |
          git remote rm origin
          git remote add --mirror=fetch origin 'https://github.com/abseil/abseil-cpp'
          git pull --prune --all || true
          git push --force --all --follow-tags 'https://github.com/jnooree/abseil-cpp'

  test-build:
    needs: mirror
    uses: ./.github/workflows/_build.yml
    with:
      ref: ${{ needs.mirror.outputs.ref }}

concurrency:
  group: mirror-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
