name: Create release

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to release"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: release

    steps:
      - id: build
        uses: ./.github/workflows/_build.yml
        with:
          ref: ${{ github.event.client_payload.ref || github.event.inputs.ref }}

      - uses: actions/download-artifact@v4
        with:
          pattern: libabsl-static-*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: libabsl-static-*.tar.gz
          repository: jnooree/abseil-cpp
          tag_name: ${{ steps.build.outputs.ref  }}
          body: "Release ${{ steps.build.outputs.ref  }}"
          prerelease: ${{ contains(steps.build.outputs.ref, '.rc') }}
          token: ${{ secrets.DEPLOY_TOKEN }}

concurrency:
  group: release-${{ github.workflow }}-${{ github.event.client_payload.ref || github.event.inputs.ref }}
  cancel-in-progress: false
