name: Create release

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to release"
        required: true

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      ref: ${{ github.event.client_payload.ref || github.event.inputs.ref }}

  release:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: release

    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: libabsl-static-*
          merge-multiple: true

      - run: |
          mkdir source-archives && cd source-archives
          curl -fL "https://github.com/jnooree/abseil-cpp/archive/refs/tags/${tag}.tar.gz" |
            tar -xz
          mv "abseil-cpp-$tag" abseil-cpp-latest
          tar -cvzf ../abseil-cpp-latest.tar.gz abseil-cpp-latest
        env:
          tag: ${{ needs.build.outputs.ref }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tar.gz"
          fail_on_unmatched_files: true
          repository: jnooree/abseil-cpp
          tag_name: ${{ needs.build.outputs.ref }}
          body: |
            Release ${{ needs.build.outputs.ref }}.
            Built with ${{ github.repository }}@${{ needs.build.outputs.build-ref }}.
          prerelease: ${{ contains(needs.build.outputs.ref, '.rc') }}
          token: ${{ secrets.DEPLOY_TOKEN }}

concurrency:
  group: release-${{ github.workflow }}-${{ github.event.client_payload.ref || github.event.inputs.ref }}
  cancel-in-progress: false
